config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'

  root 'static#home'
  get '/about', to: 'static#about', as: 'about'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :posts

  resources :tags, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  has_one :user, through: :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts

  has_many :users, through: :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, through: :posts
  has_many :tags, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    news_url = 'https://newsapi.org/v1/articles?source=cnn&sortBy=top&apiKey=c88ebd8795d44dcdb1757b869a65f72b'
    response = HTTParty.get(news_url)

    @news_data = response

    @all_post = current_user.posts
    @new_post = current_user.posts.new

  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    render html: 'show form to create new post'
  end

  def create
    Post.create(post_params)

    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    updating_post = Post.find(params[:id])
    updating_post.update(post_update_params)

    redirect_to posts_path
  end

  def destroy
    deleted_post = Post.find(params[:id])
    deleted_post.destroy

    redirect_to posts_path
  end

  private

  def post_params
     params.require(:post).permit(:title, :content, :user_id)
  end

  def post_update_params
     params.require(:post).permit(:title, :content)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @all_tags = Tag.all
    render json: @all_tags
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggiesPsql</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "partials/nav" %>
    <div class="container">
    <section class="hero">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            <h1 class="title"><%= yield(:title) %></h1>
          </h1>
        </div>
      </div>
    </section>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

  </body>


  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
          &copy Bloggies 2017
        </p>
      </div>
    </div>
  </footer>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar">
  <a class="navbar-item" href="/">
    <img src="http://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
  </a>

  <%= link_to "About", about_path, :class => "navbar-item" %>
  <%= link_to "My posts", posts_path, :class => "navbar-item" %>

  <% if current_user %>
    <!-- true -->
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-item navbar-end" %>
  <% else %>
    <!-- false -->
    <%= link_to "Login",  new_user_session_path, :class => "navbar-item" %>
    <%= link_to "Register", new_user_registration_path, :class => "navbar-item" %>
  <% end %>

</nav>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post #{@post.title}") %>

<%= form_for @post do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :Content %>
  <%= f.text_area :content %>
  <br>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, "Posts by #{current_user.name}") %>

<% @news_data['articles'].each do |article| %>
  <h3><%= article['title'] %></h3>
  <%= image_tag article['urlToImage'], width: 200 %>
  <%= article['description'] %>
  <%= link_to 'Read more..', article['url'] %>
  <br>
<% end %>

<h2>Create new post</h2>
<%= form_for @new_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <br>
  <%= f.submit %>
<% end %>

<% @all_post.each do |post| %>
  <% if post.id %>
    <h3><%= post.title %></h3>
    <%= post.content %>

    <br>
    <%= link_to "View", post_path(post) %>
    <%= link_to "Edit", edit_post_path(post) %>
    <%= link_to "Delete", post_path(post), method: :delete %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h2 class="title is-3"><%= @post.title %>
<small class="subtitle">Written by: <%= @post.user.name %></small></h2>

<p class="content"><%= @post.content %></p>

Tags:
<ul id="tags">

</ul>

<%= link_to "Edit", edit_post_path %>